### ISSUE TITLE
Karen Font is wrong

### ISSUE THREAD

**Issue by moemyintshein** [myanmarcyberyouths/myanmar-calendar#34]
![Screenshot from 2023-08-21 09-11-23](https://github.com/myanmarcyberyouths/myanmar-calendar/assets/25919243/ae85b29a-6519-4d96-ba59-b5e0f2923383)

Could you please help to check Karen's font? It's showing the wrong output on a full moon day. လါပှဲၤ (လပြည့်) . And I think Karen's font is better also displayed on the popup box.

Regards,

**Comment by amm834** [comment]
A few question related to the Karen font, the text "လါပှဲၤ" is correct in Karen? If it does I will replace that to the incorrect word.

**Comment by moemyintshein** [comment]
"လါပှဲၤ" is correct in Karen.

**Comment by amm834** [comment]
I'll fix that

**Comment by amm834** [comment]
Fixed
