### ISSUE TITLE
Wrong showing current day

### ISSUE THREAD

**Issue by kotin-lab** [myanmarcyberyouths/myanmar-calendar#35]
On browser first load and refresh, current day blue-circle mark is showing on 1day back(on past day)

![mm-calendar](https://github.com/myanmarcyberyouths/myanmar-calendar/assets/69416810/e83630ae-0e53-41c9-9ca5-47e9d2677150)

**Comment by amm834** [comment]
Timezone problem will be fixed.

**Comment by amm834** [comment]
Fixed #

**Comment by amm834** [comment]
I have been fixed but the error is still persist in the server time state. I will investigate the error.
